// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmICo2kDRlavECOFTBHy8RdNNmTH57BMw',
    appId: '1:566805698878:web:3f26213b18a0539ab2f46f',
    messagingSenderId: '566805698878',
    projectId: 'friends-e4b0e',
    authDomain: 'friends-e4b0e.firebaseapp.com',
    storageBucket: 'friends-e4b0e.firebasestorage.app',
    measurementId: 'G-WL3J4HRMVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5VBPG-UTuP7MvKANf4OKv992k_RT26sA',
    appId: '1:566805698878:android:6ce79422239f14cdb2f46f',
    messagingSenderId: '566805698878',
    projectId: 'friends-e4b0e',
    storageBucket: 'friends-e4b0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcT_0e5MnclmOIT6InHmHww0XAvydUbyk',
    appId: '1:566805698878:ios:04dd49f21f629b19b2f46f',
    messagingSenderId: '566805698878',
    projectId: 'friends-e4b0e',
    storageBucket: 'friends-e4b0e.firebasestorage.app',
    iosBundleId: 'com.example.friends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcT_0e5MnclmOIT6InHmHww0XAvydUbyk',
    appId: '1:566805698878:ios:04dd49f21f629b19b2f46f',
    messagingSenderId: '566805698878',
    projectId: 'friends-e4b0e',
    storageBucket: 'friends-e4b0e.firebasestorage.app',
    iosBundleId: 'com.example.friends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmICo2kDRlavECOFTBHy8RdNNmTH57BMw',
    appId: '1:566805698878:web:52f6037648214848b2f46f',
    messagingSenderId: '566805698878',
    projectId: 'friends-e4b0e',
    authDomain: 'friends-e4b0e.firebaseapp.com',
    storageBucket: 'friends-e4b0e.firebasestorage.app',
    measurementId: 'G-CSCLF6YVJ2',
  );
}
